spring:
  datasource:
    url: jdbc:h2:mem:maindb
  flyway:
    enabled: true
    create-schemas: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
  sql:

