spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/hw06
    username: usr
    password: pwd

  flyway:
    enabled: true
    create-schemas: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    com.zaxxer.hikari: INFO

