spring:
  data:
    mongodb:
      authentication-database: admin
      username: usr
      password: pwd
      database: hw-11
      port: 27017
      host: localhost
  logging:
    level:
      # Spring Framework
      org.springframework.web: TRACE
      org.springframework.web.filter.CommonsRequestLoggingFilter: TRACE