spring:
  data:
    mongodb:
      authentication-database: admin
      username: usr
      password: pwd
      database: hw-08
      port: 27017
      host: localhost
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.hw.mongock
  always-run: true

